# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import replicator_pb2 as replicator__pb2


class ReplicatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.synchronizer = channel.unary_stream(
        '/Replicator/synchronizer',
        request_serializer=replicator__pb2.Request.SerializeToString,
        response_deserializer=replicator__pb2.Response.FromString,
        )
    self.put = channel.unary_unary(
        '/Replicator/put',
        request_serializer=replicator__pb2.PutOperation.SerializeToString,
        response_deserializer=replicator__pb2.GetRequest.FromString,
        )
    self.delete = channel.unary_unary(
        '/Replicator/delete',
        request_serializer=replicator__pb2.DeleteOperation.SerializeToString,
        response_deserializer=replicator__pb2.GetRequest.FromString,
        )


class ReplicatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def synchronizer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def put(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReplicatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'synchronizer': grpc.unary_stream_rpc_method_handler(
          servicer.synchronizer,
          request_deserializer=replicator__pb2.Request.FromString,
          response_serializer=replicator__pb2.Response.SerializeToString,
      ),
      'put': grpc.unary_unary_rpc_method_handler(
          servicer.put,
          request_deserializer=replicator__pb2.PutOperation.FromString,
          response_serializer=replicator__pb2.GetRequest.SerializeToString,
      ),
      'delete': grpc.unary_unary_rpc_method_handler(
          servicer.delete,
          request_deserializer=replicator__pb2.DeleteOperation.FromString,
          response_serializer=replicator__pb2.GetRequest.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Replicator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
